# This is a basic workflow to help you get started with Actions

name: Polygon staging doc deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [polygon-staging]
 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: polygon-staging

      # Runs a single command using the runners shell
      - name: INSTALL
        run: rm -rf node_modules && yarn install --immutable --immutable-cache --check-cache

      # Runs a single command using the runners shell
      - name: Build
        run: yarn build

      # Runs a set of commands using the runners shell
      - name: Uploading to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.POLYGON_STAGING_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.POLYGON_STAGING_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.POLYGON_STAGING_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1' # optional: defaults to us-east-1
          SOURCE_DIR: ${{secrets.TARGET_DIRECTORY}} # optional: defaults to entire repository

      - name: invalidate cloudfront distribution and wait for completion
        uses: muratiger/invalidate-cloudfront-and-wait-for-completion-action@master
        env:
          DISTRIBUTION_ID: ${{ secrets.POLYGON_STAGING_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.POLYGON_STAGING_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.POLYGON_STAGING_AWS_SECRET_ACCESS_KEY }}
